"""Fingerprint test: pins ``quat_xyzw_to_rpy`` to the scipy extrinsic-XYZ
convention shared with the training pipeline. Fixture is generated by
``scripts/fastwam_generate_rotation_fingerprint.py``."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from fastwam.server.rotation import quat_xyzw_to_rpy


FIXTURE = Path(__file__).resolve().parent / "fixtures" / "rotation_fingerprint.json"


def _load_samples():
    payload = json.loads(FIXTURE.read_text())
    return payload["samples"]


@pytest.mark.parametrize("sample", _load_samples(), ids=lambda s: s["label"])
def test_quat_xyzw_to_rpy_matches_fingerprint(sample):
    quat = np.array(sample["quat_xyzw"], dtype=np.float64)
    expected = np.array(sample["expected_rpy"], dtype=np.float64)
    got = quat_xyzw_to_rpy(quat).astype(np.float64)
    err = float(np.max(np.abs(got - expected)))
    assert err < 1e-5, f"{sample['label']}: max abs err {err} >= 1e-5"
