name: open_door_airbot_play_back_gs
task: open_door_airbot_play_back_gs
instruction: open the door
camera_map: head_left=env2_cam,right_wrist_left=eef_wrist_cam
action_repeat: 5
train_action_hz: 20.0
max_updates: 160
stride: 32
disable_arm_randomization: true
proprio_mode: joint
proprio_dim: 7
